-- 코드를 입력하세요
SELECT    YEAR(S.SALES_DATE),
          MONTH(S.SALES_DATE),
          I.GENDER,
          COUNT(DISTINCT S.USER_ID)
FROM      ONLINE_SALE S
JOIN      USER_INFO I
ON        S.USER_ID = I.USER_ID
WHERE     GENDER IS NOT NULL
GROUP BY  YEAR(S.SALES_DATE), MONTH(S.SALES_DATE), I.GENDER
ORDER BY  YEAR(S.SALES_DATE), MONTH(S.SALES_DATE), I.GENDER