SELECT    A.CAR_ID,
          C.CAR_TYPE,
          ROUND(C.DAILY_FEE * 30 * (100-DISCOUNT_RATE) / 100) AS FEE
FROM      (SELECT DISTINCT H.CAR_ID
           FROM   CAR_RENTAL_COMPANY_RENTAL_HISTORY H
           WHERE  1=1
           AND    H.CAR_ID NOT IN (SELECT DISTINCT H.CAR_ID
                                   FROM   CAR_RENTAL_COMPANY_RENTAL_HISTORY H
                                   WHERE  (END_DATE BETWEEN "2022-11-01" and "2022-11-30"
                                   OR      START_DATE BETWEEN "2022-11-01" and "2022-11-30"
                                   OR      END_DATE > "2022-11-30" and START_DATE < "2022-11-01"))
          ) A
LEFT JOIN CAR_RENTAL_COMPANY_CAR C
ON        A.CAR_ID = C.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON        (C.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE = '30일 이상')
WHERE     1=1
AND       (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV')
AND       ROUND(C.DAILY_FEE * 30 * (100-DISCOUNT_RATE) / 100) BETWEEN 500000 AND 2000000
ORDER BY  FEE DESC, CAR_TYPE, CAR_ID DESC