-- 코드를 입력하세요
SELECT A.CART_ID
FROM   CART_PRODUCTS A
JOIN   (SELECT CART_ID
        FROM   CART_PRODUCTS
        WHERE  NAME = 'Milk') B
ON     A.CART_ID = B.CART_ID
JOIN   (SELECT CART_ID
        FROM   CART_PRODUCTS
        WHERE  NAME = 'Yogurt') C
ON     A.CART_ID = C.CART_ID
GROUP BY A.CART_ID
ORDER BY A.CART_ID