-- 코드를 입력하세요
SELECT MONTH(B.START_DATE) AS MONTH,
       A.CAR_ID,
       COUNT(*) AS RECORDS
FROM   (SELECT   CAR_ID
        FROM     CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE    1=1
        AND      DATE_FORMAT(START_DATE, '%Y%m') >= '202208'
        AND      DATE_FORMAT(START_DATE, '%Y%m') <= '202210'
        GROUP BY CAR_ID
        HAVING   COUNT(*) >= 5
       ) AS A
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B
ON        A.CAR_ID = B.CAR_ID
WHERE     1=1
AND       DATE_FORMAT(B.START_DATE, '%Y%m') >= '202208'
AND       DATE_FORMAT(B.START_DATE, '%Y%m') <= '202210'
GROUP BY  B.CAR_ID, MONTH(B.START_DATE)
ORDER BY  MONTH, A.CAR_ID DESC