-- 코드를 입력하세요
SELECT    B.CATEGORY,
          SUM(S.SALES)
FROM      BOOK_SALES S
LEFT JOIN BOOK B
ON        S.BOOK_ID = B.BOOK_ID
WHERE     1=1
AND       YEAR(S.SALES_DATE) = '2022'
AND       MONTH(S.SALES_DATE) = '1'
GROUP BY  B.CATEGORY
ORDER BY  B.CATEGORY