-- 코드를 입력하세요
SELECT    C.AUTHOR_ID,
          C.AUTHOR_NAME,
          B.CATEGORY,
          SUM(A.SALES * B.PRICE)
FROM      BOOK_SALES A
LEFT JOIN BOOK B
ON        A.BOOK_ID = B.BOOK_ID
LEFT JOIN AUTHOR C
ON        B.AUTHOR_ID = C.AUTHOR_ID
WHERE     DATE_FORMAT(A.SALES_DATE, '%Y%m') = '202201'
GROUP BY  C.AUTHOR_ID, B.CATEGORY
ORDER BY  C.AUTHOR_ID, B.CATEGORY DESC
