-- 코드를 입력하세요
SELECT    P.PRODUCT_CODE,
          SUM(P.PRICE * SALES_AMOUNT)
FROM      OFFLINE_SALE O
LEFT JOIN PRODUCT P
ON        O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY  P.PRODUCT_CODE
ORDER BY  SUM(P.PRICE * SALES_AMOUNT) DESC, P.PRODUCT_CODE