-- 코드를 입력하세요
SELECT B.CAR_ID,
       IFNULL(A.AVAILABILITY, '대여 가능')
FROM   (SELECT CAR_ID,
               '대여중' AS AVAILABILITY
        FROM   CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE  DATE_FORMAT(START_DATE, '%Y%m%d') <= '20221016'
        AND    DATE_FORMAT(END_DATE, '%Y%m%d') >= '20221016'
       ) A
RIGHT OUTER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
ON B.CAR_ID = A.CAR_ID
GROUP BY B.CAR_ID
ORDER BY B.CAR_ID DESC