-- 코드를 입력하세요
SELECT   A.HISTORY_ID,
         CASE WHEN A.DURATION_TYPE IS NULL THEN A.DAILY_FEE * A.DATE
              ELSE ROUND(A.DAILY_FEE * A.DATE * (100 - P.DISCOUNT_RATE) / 100, 0)
         END AS FEE
FROM     (SELECT H.HISTORY_ID,
                 C.DAILY_FEE,
                 C.CAR_TYPE,
                 DATEDIFF(H.END_DATE, H.START_DATE)+1 AS DATE,
                 CASE WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 90 THEN '90일 이상'
                      WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 30 THEN '30일 이상'
                      WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 7 THEN '7일 이상'
                      ELSE NULL
                 END AS DURATION_TYPE
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
          LEFT JOIN CAR_RENTAL_COMPANY_CAR C
          ON H.CAR_ID = C.CAR_ID
          WHERE 1=1
          AND C.CAR_TYPE = '트럭') AS A
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON        (A.DURATION_TYPE = P.DURATION_TYPE AND A.CAR_TYPE = P.CAR_TYPE)
ORDER BY  FEE DESC, A.HISTORY_ID DESC